-- MyTix load.sql
-- Bulk-loads the sample data into the mytix schema. Run it after schema.sql.
--
-- Generated by tools/generate_data.py. We use plain INSERT statements so this
-- runs anywhere with a bare `mysql < sql/load.sql`, no flags needed. If load
-- time ever becomes a problem, switch to the LOAD DATA LOCAL INFILE variant and
-- run the client with --local-infile=1 (and server local_infile=ON).

USE mytix;

-- (populated by the data generator - not yet run)
